# Generated by Django 5.0.6 on 2024-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_documents_link_documents_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='link')),
            ],
            options={
                'verbose_name': 'Видеоматериал',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
    ]
