# Generated by Django 5.0.6 on 2024-06-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('material', models.FileField(upload_to='metodics', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Методичка',
                'verbose_name_plural': 'Методички',
            },
        ),
    ]
