# Generated by Django 5.0.6 on 2024-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
